FROM node:lts-alpine

# Install file-watching prerequisites
RUN apk add  \
  bash \
  coreutils \
  busybox-extras \
  inotify-tools

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install -g ts-node nodemon typescript && npm install --legacy-peer-deps

COPY . .

# Set env variable inside container (can be overridden by Compose)
ARG CEN_CMS_API_PORT
ENV CEN_CMS_API_PORT=${CEN_CMS_API_PORT}

RUN chown -R node /usr/src/app

EXPOSE ${CEN_CMS_API_PORT}

USER node

CMD ["npm", "run", "dev"]
