FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install -g ts-node nodemon typescript && npm install --legacy-peer-deps

COPY . .

# Set env variable inside container (can be overridden by Compose)
ARG CEN_CMS_API_PORT
ENV CEN_CMS_API_PORT=${CEN_CMS_API_PORT}

EXPOSE ${CEN_CMS_API_PORT}

USER node

CMD ["nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "ts-node", "src/index.ts"]
